services:
  db:
    image: postgres:17
    container_name: postgres-db

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      produtos:
        driver: default
        enable_ipv6: false            
        driver_opts:
          parent: eth0
        ipam:
          config:
            - subnet: 172.22.0.0/16
              gateway: 172.22.0.1 
              ip_range: 172.22.0.1/30
  
  app:
    build: .
    container_name: curso-api

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: